## Filename : lookups.R
## Description : Define dataframes for lookup tables

other_species_df <- data.frame(
    code = c(
        "none",
        "blue_tit",
        "chiff_chaff",
        "chaffinch",
        "coal_tit",
        "dunnock",
        "goldcrest",
        "great_tit",
        "nuthatch",
        "robin",
        "siskin",
        "tree_creeper",
        "unknown_tit",
        "woodpecker",
        "wren",
        "willow_warbler"),
    description = c(
        "None",
        "Blue Tit (bt)",
        "Chiff Chaff (cc)",
        "Chaffinch (ch)",
        "Coal Tit (ct)",
        "Dunnock (du)",
        "Goldcrest (gc)",
        "Great Tit (gt)",
        "Nuthatch (nh)",
        "Robin (rb)",
        "Siskin (sk)",
        "Tree Creeper (tc)",
        "Unknown Tit (ut)",
        "Greater Spotted Woodpecker (wp)",
        "Wren (wr)",
        "Willow Warbler (ww)"
    )
)

rings_df <- data.frame(
    code = c(
        "None",
        "BTO",
        "B",
        "D",
        "F",
        "G",
        "M",
        "N",
        "O",
        "P",
        "R",
        "U",
        "W",
        "Y",
        "Sd",
        "Sg",
        "Sn",
        "So",
        "Sp",
        "Sr",
        "Sw",
        "Sy",
        "bm",
        "dg",
        "do",
        "dr",
        "dy",
        "gd",
        "gn",
        "mb",
        "ng",
        "no",
        "nr",
        "od",
        "on",
        "rd",
        "rn",
        "ry",
        "yd",
        "yr",
        "B*",
        "G*",
        "N*",
        "P*",
        "R*",
        "W*",
        "Y*"),
    description = c(
        NA,
        "BTO",
        "Light blue (B)",
        "Dark blue (D)",
        "Flamingo (/Old light pink) (F)",
        "Green (G)",
        "Mauve (M)",
        "Black (N)",
        "Orange (O)",
        "Pink (P)",
        "Red (R)",
        "Umber (/brown) (U)",
        "White (W)",
        "Yellow (Y)",
        "Striped dark blue & yellow (Sd)",
        "Striped light green & dark green / green & white (Sg)",
        "Striped black & white (Sn)",
        "Stripped orange & white (So)",
        "Striped black & pink (Sp)",
        "Striped red & white (Sr)",
        "Striped dark blue & white(Sw)",
        "Striped yellow & red (Sy)",
        "Split light  blue & mauve (bm)",
        "Split dark blue & green (dg)",
        "Split dark blue & orange (do)",
        "Split dark blue & red (dr)",
        "Split dark blue & yellow (dy)",
        "Split green & dark blue (gd)",
        "Split green & black (gn)",
        "Split mauve & light blue (mb)",
        "Split black & green (ng)",
        "Split black & orange (no)",
        "Split black & red (nr)",
        "Split orange & dark blue (od)",
        "Split orange & black (on)",
        "Split red & dark blue (rd)",
        "Split red & black (rn)",
        "Split red & yellow (ry)",
        "Split yellow & dark blue (yd)",
        "Split yellow & red (yr)",
        "Pit-tag light blue (B*)",
        "Pit-tag green (G*)",
        "Pit-tag black (N*)",
        "Pit-tag pink (P*)",
        "Pit-tag red (R*)",
        "Pit-tag white (W*)",
        "Pit-tag yellow (Y*)"
    )
)

person_df <- data.frame(
    code = c("SB", "LN", "MJ", "ND"),
    forename = c("Sarah (SB)", "Luke (LN)", "Micko (MJ)", "Nina (ND)") ##,
    ## surname = character("", "", "", "")
)

section_df <- data.frame(
    code = c("RV",
             "BB",
             "NH",
             "FH"),
    description = c("Rivelin Valley (RV)",
                    "Black Brook (BB)",
                    "North Hagg (NH)",
                    "Fox Hagg (FH)"))

## Conditions
conditions_df <- data.frame(
    code = c("sunny", "partly_cloudy", "cloudy_grey", "foggy", "windy", "light_rain", "really_rainy"),
    description = c("Sunny", "Partly cloudy", "Cloudy/ grey", "Foggy", "Windy", "Light rain", "Really rainy")
)

## Visibility
visibility_df <- data.frame(
    code = c("perfect", "good", "average", "mediocre"),
    description = c("Perfect", "Good", "Average", "Mediocre")
)

## Interactions
interactions_df <- data.frame(
    code = c("foraging_together", "a_chasing_b", "b_chasing_a", "close_but_not_interacting",
             "other"),
    description = c("Foraging together", "A chasing B", "B chasing A", "Near but not interacting", "Other (see notes)")
)

## Ring Combinations
colour_ring_df <- data.frame(
    code = c("None", "BTO L", "BTO R", "B*BL","B*BR","B*DL","B*DR","B*GL","B*GR","B*ML","B*NL","B*NR","B*OL","B*OR","B*PL",
             "B*RL","B*SdL","B*SdR","B*SgL","B*SgR","B*SnL","B*SnR","B*SpL","B*SpR","B*SrR",
             "B*SyL","B*SyR", "B*UL", "B*WR", "B*YL", "B*gdR", "B*ngL", "B*ngR", "BBR", "BMR", "BOL", "BR*R", "BRR",
    "BSnR", "BSpL", "BUR", "BYR", "BbmL", "BbmR", "BgdL", "BgdR", "BmbL", "BmbR", "BngL", "BngR", "ByrR", "DB*L",
    "DB*R", "DDL", "DDR", "DFL", "DG*R", "DGR", "DML", "DMR", "DN*R", "DNL", "DOL", "DOR", "DP*L", "DP*R", "DRL", "DRR",
    "DSdL", "DSdR", "DSgR", "DSnL", "DSnR", "DSpL", "DSpR", "DUL", "DW*L", "DWR", "DY*L", "DYL", "DYR", "DbmL", "DbmR",
    "DgdL", "DgdR", "DmbL", "DmbR", "DngL", "DngR", "DryR", "DsdR", "FB*L", "FB*R", "FDL", "FDR", "FFL", "FG*L", "FG*R",
    "FN*R", "FOR", "FP*L", "FP*R", "FR*L", "FSdL", "FSdR", "FSnL", "FSnR", "FSpL", "FSpR", "FY*L", "FYR", "FbmL",
    "FbmR", "FgdL", "FgdR", "FmbL", "FmbR", "FngL", "FngR", "G*DL", "G*DR", "G*FR", "G*GL", "G*GR", "G*ML", "G*MR",
    "G*OR", "G*PL", "G*PR", "G*R", "G*RL", "G*RR", "G*SdL", "G*SgL", "G*SgR", "G*SnL", "G*SnR", "G*SpL", "G*SpR",
    "G*SrL", "G*SrR", "G*SyL", "G*SyR", "G*UL", "G*drL", "G*gdR", "G*gnR", "G*mbL", "G*ngR", "GBL", "GBR", "GFL", "GML",
    "GNL", "GNR", "GOL", "GOR", "GPR", "GRL", "GSdR", "GSnR", "GSpL", "GSpR", "GUR", "GW*L", "GWL", "GWR", "GYL", "GYR",
    "GbmL", "GbmR", "GgdL", "GgdR", "GmbR", "GngL", "GngR", "GryR", "MB*L", "MB*R", "MBR", "MDL", "MDR", "MG*R", "MGR",
    "MML", "MMR", "MNL", "MNR", "MOL", "MP*L", "MP*R", "MR*L", "MR*R", "MSdL", "MSdR", "MSgL", "MSnL", "MSnR", "MSpL",
    "MSpR", "MUL", "MUR", "MW*L", "MWR", "MYL", "MYR", "MbmL", "MbmR", "MgdL", "MgdR", "MmbL", "MmbR", "MngL", "MngR",
    "MryR", "N*BL", "N*BR", "N*DR", "N*FL", "N*FR", "N*L", "N*MR", "N*PR", "N*R", "N*RR", "N*SdL", "N*SdR", "N*SgL",
    "N*SgR", "N*SnL", "N*SnR", "N*SpL", "N*SpR", "N*SrL", "N*SrR", "N*SyL", "N*SyR", "N*UL", "N*UR", "N*WL", "N*YR",
    "N*gdL", "N*gdR", "N*mbL", "N/A", "NDL", "NGL", "NGR", "NNL", "NNR", "NOL", "NOR", "NPL", "NPR", "NRL", "NSnR",
    "NSpL", "NSpR", "NW*R", "NWR", "NYL", "NYR", "NbmL", "NbmR", "NgdL", "NgdR", "NmbR", "NngL", "NngR", "OB*L", "OB*R",
    "OBL", "ODL", "ODR", "OFR", "OG*R", "OGL", "OML", "OMR", "ON*L", "ONR", "OOL", "OOR", "OPL", "OPR", "OR*L", "ORL",
    "ORR", "OSdL", "OSdR", "OSgR", "OSnL", "OSnR", "OSpL", "OSpR", "OUR", "OW*R", "OWL", "OY*L", "OY*R", "OYL", "OYR",
    "ObmL", "ObmR", "OgdL", "OgdR", "OmbL", "OmbR", "OngL", "OngR", "OryR", "P*DR", "P*FL", "P*GL", "P*GR", "P*MR",
    "P*NR", "P*OL", "P*OR", "P*PR", "P*RR", "P*SdL", "P*SdR", "P*SgL", "P*SnL", "P*SnR", "P*SpR", "P*SrL", "P*SrR",
    "P*SyL", "P*SyR", "P*UL", "P*UR", "P*YL", "P*gdR", "P*gnL", "P*mbL", "PBL", "PBR", "PDL", "PML", "PMR", "PNL",
    "POL", "POR", "PSpL", "PSpR", "PWL", "PYL", "PYR", "PbmL", "PbmR", "PgdL", "PgdR", "PmbR", "PngL", "PngR", "PryR",
    "R*DL", "R*FL", "R*FR", "R*L", "R*MR", "R*NL", "R*OR", "R*PR", "R*SdL", "R*SgL", "R*SgR", "R*SnL", "R*SnR", "R*SpR",
    "R*SrR", "R*SyL", "R*WL", "R*WR", "R*YR", "R*gnR", "R*mbL", "RBL", "RBR", "RDL", "RGL", "RGR", "RML", "RMR", "RNR",
    "ROL", "RPL", "RRL", "RRR", "RSdR", "RSnR", "RSpL", "RSpR", "RWL", "RYL", "RYR", "RbmL", "RbmR", "RdgL", "RdrL",
    "RgdL", "RmbR", "RngL", "RngR", "SdB*L", "SdFL", "SdG*L", "SdML", "SdN*L", "SdN*R", "SdOL", "SdP*L", "SdP*R",
    "SdR*L", "SdR*R", "SdRL", "SdUL", "SdW*L", "SdW*R", "SdY*L", "SdY*R", "SgB*L", "SgB*R", "SgG*L", "SgG*R", "SgN*L",
    "SgN*R", "SgP*L", "SgR*L", "SgR*R", "SgTL", "SgW*L", "SgW*R", "SnB*L", "SnBL", "SnBR", "SnDL", "SnDR", "SnFL",
    "SnFR", "SnG*L", "SnG*R", "SnGR", "SnML", "SnMR", "SnN*R", "SnNL", "SnOL", "SnOR", "SnP*L", "SnP*R", "SnPR",
    "SnR*L", "SnR*R", "SnUL", "SnUR", "SnW*L", "SnW*R", "SnWR", "SnY*L", "SnY*R", "SnYR", "SpB*L", "SpB*R", "SpBL",
    "SpDL", "SpDR", "SpFL", "SpFR", "SpG*L", "SpGR", "SpML", "SpMR", "SpN*R", "SpNL", "SpNR", "SpOL", "SpOR", "SpP*L",
    "SpP*R", "SpPL", "SpR*R", "SpRL", "SpRR", "SpSnL", "SpUL", "SpUR", "SpW*R", "SpWR", "SpY*L", "SpY*R", "SpYR",
    "SrB*L", "SrB*R", "SrG*L", "SrG*R", "SrN*L", "SrN*R", "SrP*L", "SrP*R", "SrR*L", "SrR*R", "SrW*L", "SrW*R", "SrY*L",
    "SrY*R", "SyB*L", "SyB*R", "SyG*L", "SyN*L", "SyP*L", "SyP*R", "SyR*L", "SyR*R", "SyW*L", "SyW*R", "SyY*L", "SyY*R",
    "TRL", "UB*L", "UB*R", "UDL", "UDR", "UFL", "UFR", "UG*L", "UG*R", "UL", "UML", "UMR", "UN*R", "UNL", "UOL",
    "UOR", "UP*L", "UP*R", "UPR", "UR*L", "UR*R", "USdL", "USdR", "USnL", "USnR", "USpL", "USpR", "UUL", "UUR", "UW*R",
    "UWL", "UY*L", "UYL", "UYR", "UbmL", "UbmR", "UgdL", "UgdR", "UgnR", "UmbL", "UmbR", "UngL", "UngR", "W*BL", "W*FL",
    "W*FR", "W*GR", "W*MR", "W*NL", "W*OR", "W*PL", "W*PR", "W*RR", "W*SdL", "W*SdR", "W*SgL", "W*SnL", "W*SnR",
    "W*SpR", "W*SrR", "W*SyL", "W*SyR", "W*gdR", "W*gnL", "W*gnR", "W*mbL", "WBL", "WBR", "WDL", "WGL", "WML", "WNL",
    "WNR", "WPL", "WRL", "WSpL", "WUR", "WWL", "WWR", "WYL", "WYR", "WbmL", "WbmR", "WgdL", "WgdR", "WmbR", "WngL",
    "WngR", "WryR", "Y*DR", "Y*FL", "Y*NR", "Y*PL", "Y*RL", "Y*RR", "Y*SdL", "Y*SgL", "Y*SgR", "Y*SnL", "Y*SnR",
    "Y*SpL", "Y*SpR", "Y*SrR", "Y*SyL", "Y*SyR", "Y*UL", "Y*YR", "Y*gdR", "YBL", "YBR", "YDL", "YFL", "YFR", "YGL",
    "YML", "YMR", "YNL", "YNR", "YOL", "YOR", "YPL", "YSdL", "YUR", "YWL", "YWR", "YbmL", "YbmR", "YgdL", "YgdR",
    "YmbL", "YmbR", "YngL", "YngR", "YryR", "dg*PL", "dgB*L", "dgB*R", "dgG*L", "dgG*R", "dgN*R", "dgP*R", "dgR*L",
    "gdB*L", "gdB*R", "gdG*L", "gdG*R", "gdN*L", "gdN*R", "gdP*L", "gdP*R", "gnBL", "gnBR", "gnDL", "gnDR", "gnFL",
    "gnFR", "gnGL", "gnGR", "gnML", "gnMR", "gnNR", "gnOL", "gnOR", "gnP*R", "gnPL", "gnPR", "gnRL", "gnRR", "gnUL",
    "gnUR", "gnWL", "gnWR", "gnYR", "mbB*L", "mbG*L", "mbN*L", "mbP*R", "ngBL", "ngBR", "ngDL", "ngDR", "ngFL", "ngFR",
    "ngGL", "ngGR", "ngML", "ngMR", "ngNL", "ngNR", "ngOL", "ngOR", "ngPL", "ngPR", "ngRL", "ngRR", "ngUR", "ngWR",
    "noR*R", "ryBR", "ryDR", "ryFR", "ryGR"))
