## Filename : lookups.R
## Description : Define dataframes for lookup tables

other_species_df <- data.frame(
  code = c("none",
           "blue_tit",
           "chiff_chaff",
           "chaffinch",
           "coal_tit",
           "dunnock",
           "goldcrest",
           "great_tit",
           "nuthatch",
           "robin",
           "siskin",
           "tree_creeper",
           "unknown_tit",
           "woodpecker",
           "wren",
           "willow_warbler"),
  description = c("None",
                  "Blue Tit (bt)",
                  "Chiff Chaff (cc)",
                  "Chaffinch (ch)",
                  "Coal Tit (ct)",
                  "Dunnock (du)",
                  "Goldcrest (gc)",
                  "Great Tit (gt)",
                  "Nuthatch (nh)",
                  "Robin (rb)",
                  "Siskin (sk)",
                  "Tree Creeper (tc)",
                  "Unknown Tit (ut)",
                  "Greater Spotted Woodpecker (wp)",
                  "Wren (wr)",
                  "Willow Warbler (ww)")
)

valid_rings_df <- data.frame(
  code = c("None",
           "BTO",
           "B",
           "D",
           "F",
           "G",
           "M",
           "N",
           "O",
           "P",
           "R",
           "U",
           "W",
           "Y",
           "Sd",
           "Sg",
           "Sn",
           "So",
           "Sp",
           "Sr",
           "Sw",
           "Sy",
           "bm",
           "dg",
           "do",
           "dr",
           "dy",
           "gd",
           "gn",
           "mb",
           "ng",
           "no",
           "nr",
           "od",
           "on",
           "rd",
           "rn",
           "ry",
           "yd",
           "yr",
           "B*",
           "G*",
           "N*",
           "P*",
           "R*",
           "W*",
           "Y*"),
  description = c("None",
                  "BTO",
                  "Light blue (B)",
                  "Dark blue (D)",
                  "Flamingo (/Old light pink) (F)",
                  "Green (G)",
                  "Mauve (M)",
                  "Black (N)",
                  "Orange (O)",
                  "Pink (P)",
                  "Red (R)",
                  "Umber (/brown) (U)",
                  "White (W)",
                  "Yellow (Y)",
                  "Striped dark blue & yellow (Sd)",
                  "Striped light green & dark green / green & white (Sg)",
                  "Striped black & white (Sn)",
                  "Stripped orange & white (So)",
                  "Striped black & pink (Sp)",
                  "Striped red & white (Sr)",
                  "Striped dark blue & white(Sw)",
                  "Striped yellow & red (Sy)",
                  "Split light  blue & mauve (bm)",
                  "Split dark blue & green (dg)",
                  "Split dark blue & orange (do)",
                  "Split dark blue & red (dr)",
                  "Split dark blue & yellow (dy)",
                  "Split green & dark blue (gd)",
                  "Split green & black (gn)",
                  "Split mauve & light blue (mb)",
                  "Split black & green (ng)",
                  "Split black & orange (no)",
                  "Split black & red (nr)",
                  "Split orange & dark blue (od)",
                  "Split orange & black (on)",
                  "Split red & dark blue (rd)",
                  "Split red & black (rn)",
                  "Split red & yellow (ry)",
                  "Split yellow & dark blue (yd)",
                  "Split yellow & red (yr)",
                  "Pit-tag light blue (B*)",
                  "Pit-tag green (G*)",
                  "Pit-tag black (N*)",
                  "Pit-tag pink (P*)",
                  "Pit-tag red (R*)",
                  "Pit-tag white (W*)",
                  "Pit-tag yellow (Y*)")
)

person_df <- data.frame(
  code = c("SB", "LN", "MJ", "ND"),
  synonyms = c("SJB", "", "", "NDR"),  ## Comma-separated list of synonyms used in GPS filenames
  forename = c("Sarah (SB)", "Luke (LN)", "Micko (MJ)", "Nina (ND)") ##,
  ## surname = character("", "", "", "")
)

section_df <- data.frame(
  code = c("RV", "BB", "NH", "FH"),
  description = c("Rivelin Valley (RV)",
                  "Black Brook (BB)",
                  "North Hagg (NH)",
                  "Fox Hagg (FH)"))

## Conditions
conditions_df <- data.frame(
  code = c("sunny", "partly_cloudy", "cloudy_grey", "foggy", "windy", "light_rain", "really_rainy"),
  description = c("Sunny", "Partly cloudy", "Cloudy/ grey", "Foggy", "Windy", "Light rain", "Really rainy")
)

## Visibility
visibility_df <- data.frame(
  code = c("perfect", "good", "average", "mediocre"),
  description = c("Perfect", "Good", "Average", "Mediocre")
)

## Interactions
interactions_df <- data.frame(
    code = c("foraging_together", "a_chasing_b", "b_chasing_a", "close_but_not_interacting", "other"),
    description = c("Foraging together", "A chasing B", "B chasing A", "Near but not interacting", "Other (see notes)")
)

## Ring Combinations
valid_ring_combinations_df <- data.frame(
  code = c("None", "BTO L", "BTO R","B*BL", "B*BR", "B*DL", "B*DR", "B*gdR", "B*GL", "B*GR", "B*ML", 
              "B*ngL", "B*ngR", "B*NL", "B*NR", "B*OL", "B*OR", "B*PL", "B*RL", 
              "B*SdL", "B*SdR", "B*SgL", "B*SgR", "B*SnL", "B*SnR", "B*SpL", 
              "B*SpR", "B*SrR", "B*SyL", "B*SyR", "B*UL", "B*WR", "B*YL", "BBL", 
              "BbmL", "BbmR", "BBR", "BdgL", "BdgR", "BDL", "BDR", "BdrL", 
              "BdyL", "BFL", "BFR", "BgdL", "BGL", "BgnL", "BgnR", "bmBL", 
              "BmbL", "bmBR", "BmbR", "bmDL", "bmDR", "bmGL", "bmGR", "bmMR", 
              "bmNL", "bmNR", "bmOL", "bmOR", "bmPL", "BMR", "bmRL", "bmRR", 
              "bmUL", "bmUR", "bmWL", "bmWR", "bmYL", "bmYR", "BngL", "BngR", 
              "BnoL", "BNR", "BOL", "BonL", "BOR", "BPL", "BPR", "BR*R", "BRL", 
              "BRR", "BryR", "BSdL", "BSdR", "BSgR", "BSnL", "BSnR", "BSpL", 
              "BSpR", "BUR", "BWL", "BWR", "BYL", "BYR", "ByrL", "ByrR", "DB*L", 
              "DB*R", "DbmL", "DbmR", "DBR", "DdgL", "DdgR", "DDL", "DDR", 
              "DdrL", "DdyL", "DFL", "dg*PL", "DG*R", "dgB*L", "dgB*R", "dgBL", 
              "dgBR", "dgDL", "DgdL", "dgDR", "DgdR", "dgG*L", "dgG*R", "dgGL", 
              "dgGR", "DGL", "dgML", "dgMR", "dgN*R", "dgNL", "dgNR", "dgOL", 
              "dgOR", "dgP*R", "dgPL", "dgPR", "DGR", "dgR*L", "dgRL", "dgRR", 
              "dgUL", "dgUR", "dgWL", "dgWR", "dgYL", "dgYR", "DmbL", "DmbR", 
              "DML", "DMR", "DN*R", "DngL", "DngR", "DNL", "DnoL", "DNR", "DOL", 
              "DonL", "DOR", "DP*L", "DP*R", "DPL", "DPR", "DrdL", "DRL", "DRR", 
              "DryL", "DryR", "DSdL", "DSdR", "DSgL", "DSgR", "DSnL", "DSnR", 
              "DSpL", "DSpR", "DUL", "DW*L", "DWR", "DY*L", "DYL", "DYR", "DyrL", 
              "DyrR", "FB*L", "FB*R", "FbmL", "FbmR", "FDL", "FDR", "FFL", 
              "FG*L", "FG*R", "FgdL", "FgdR", "FmbL", "FmbR", "FN*R", "FngL", 
              "FngR", "FOR", "FP*L", "FP*R", "FR*L", "FSdL", "FSdR", "FSnL", 
              "FSnR", "FSpL", "FSpR", "FY*L", "FYR", "G*DL", "G*DR", "G*drL", 
              "G*FR", "G*gdR", "G*GL", "G*gnR", "G*GR", "G*mbL", "G*ML", "G*MR", 
              "G*ngR", "G*OR", "G*PL", "G*PR", "G*R", "G*RL", "G*RR", "G*SdL", 
              "G*SgL", "G*SgR", "G*SnL", "G*SnR", "G*SpL", "G*SpR", "G*SrL", 
              "G*SrR", "G*SyL", "G*SyR", "G*UL", "GBL", "GbmL", "GbmR", "GBR", 
              "gdB*L", "gdB*R", "gdBL", "gdBR", "gdDL", "gdDR", "gdG*L", "gdG*R", 
              "gdGL", "GdgL", "gdGR", "GdgR", "GDL", "gdML", "gdMR", "gdN*L", 
              "gdN*R", "gdNL", "gdNR", "gdOL", "gdOR", "gdP*L", "gdP*R", "gdPL", 
              "gdPR", "GDR", "gdRL", "gdRR", "gdUL", "gdWL", "gdWR", "gdYL", 
              "GdyL", "GFL", "GgdL", "GgdR", "GGL", "GgnL", "GmbR", "GML", 
              "GMR", "gnBL", "gnBR", "gnDL", "gnDR", "gnFL", "gnFR", "gnGL", 
              "GngL", "gnGR", "GngR", "GNL", "gnML", "gnMR", "gnNL", "gnNR", 
              "gnOL", "GnoL", "gnOR", "gnPL", "gnPR", "GNR", "gnRL", "gnRR", 
              "gnUL", "gnUR", "gnWL", "gnWR", "gnYL", "gnYR", "GOL", "GonL", 
              "GOR", "GPL", "GPR", "GRL", "GRR", "GryL", "GryR", "GSdL", "GSdR", 
              "GSgL", "GSgR", "GSnL", "GSnR", "GSpL", "GSpR", "GUL", "GUR", 
              "GW*L", "GWL", "GWR", "GYL", "GYR", "GyrL", "GyrR", "MB*L", "MB*R", 
              "mbB*L", "mbBL", "mbBR", "mbDL", "mbDR", "mbG*L", "mbGL", "mbGR", 
              "MBL", "mbML", "MbmL", "mbMR", "MbmR", "mbN*L", "mbNL", "mbNR", 
              "mbOL", "mbOR", "mbP*R", "mbPL", "mbPR", "MBR", "mbRL", "mbRR", 
              "mbUR", "mbWL", "mbWR", "mbYR", "MdgL", "MdgR", "MDL", "MDR", 
              "MdrL", "MdyL", "MG*R", "MgdL", "MgdR", "MGL", "MGR", "MmbL", 
              "MmbR", "MML", "MMR", "MngL", "MngR", "MNL", "MnoL", "MNR", "MOL", 
              "MP*L", "MP*R", "MPL", "MPR", "MR*L", "MR*R", "MrdL", "MRL", 
              "MryR", "MSdL", "MSdR", "MSgL", "MSgR", "MSnL", "MSnR", "MSpL", 
              "MSpR", "MUL", "MUR", "MW*L", "MWR", "MYL", "MYR", "MyrL", "MyrR", 
              "N*BL", "N*BR", "N*DR", "N*FL", "N*FR", "N*gdL", "N*gdR", "N*L", 
              "N*mbL", "N*MR", "N*PR", "N*R", "N*RR", "N*SdL", "N*SdR", "N*SgL", 
              "N*SgR", "N*SnL", "N*SnR", "N*SpL", "N*SpR", "N*SrL", "N*SrR", 
              "N*SyL", "N*SyR", "N*UL", "N*UR", "N*WL", "N*YR", "NBL", "NbmL", 
              "NbmR", "NBR", "NdgL", "NdgR", "NDL", "NdrL", "NdyL", "ngBL", 
              "ngBR", "ngDL", "NgdL", "ngDR", "NgdR", "ngFL", "ngFR", "ngGL", 
              "ngGR", "NGL", "ngML", "ngMR", "ngNL", "NgnL", "ngNR", "NgnR", 
              "ngOL", "ngOR", "ngPL", "ngPR", "NGR", "ngRL", "ngRR", "ngUL", 
              "ngUR", "ngWL", "ngWR", "ngYL", "ngYR", "NmbR", "NML", "NMR", 
              "NngL", "NngR", "NNL", "NnoL", "NNR", "noBL", "noBR", "noDL", 
              "noDR", "noGL", "noGR", "NOL", "noML", "noMR", "noNL", "noNR", 
              "noOL", "noOR", "noPL", "noPR", "NOR", "noR*R", "noWR", "noYR", 
              "NPL", "NPR", "NRL", "NRR", "NryR", "NSdL", "NSdR", "NSgL", "NSgR", 
              "NSnL", "NSnR", "NSpL", "NSpR", "NUL", "NUR", "NW*R", "NWR", 
              "NYL", "NYR", "NyrL", "NyrR", "OB*L", "OB*R", "OBL", "ObmL", 
              "ObmR", "OBR", "OdgL", "OdgR", "ODL", "ODR", "OdrL", "OdyL", 
              "OFR", "OG*R", "OgdL", "OgdR", "OGL", "OGR", "OmbL", "OmbR", 
              "OML", "OMR", "ON*L", "onBL", "onDL", "onGL", "OngL", "OngR", 
              "ONL", "onML", "onNL", "onOL", "OnoL", "onPL", "ONR", "onRL", 
              "OOL", "OonL", "OOR", "OPL", "OPR", "OR*L", "ORL", "ORR", "OryR", 
              "OSdL", "OSdR", "OSgL", "OSgR", "OSnL", "OSnR", "OSpL", "OSpR", 
              "OUR", "OW*R", "OWL", "OY*L", "OY*R", "OYL", "OYR", "OyrL", "P*DR", 
              "P*FL", "P*gdR", "P*GL", "P*gnL", "P*GR", "P*mbL", "P*MR", "P*NR", 
              "P*OL", "P*OR", "P*PR", "P*RR", "P*SdL", "P*SdR", "P*SgL", "P*SnL", 
              "P*SnR", "P*SpR", "P*SrL", "P*SrR", "P*SyL", "P*SyR", "P*UL", 
              "P*UR", "P*YL", "PBL", "PbmL", "PbmR", "PBR", "PdgL", "PdgR", 
              "PDL", "PDR", "PdrL", "PdyL", "PFR", "PgdL", "PgdR", "PgnR", 
              "PGR", "PmbR", "PML", "PMR", "PngL", "PngR", "PNL", "PnoL", "POL", 
              "PonL", "POR", "PPL", "PPR", "PrdL", "PRL", "PRR", "PryR", "PSdL", 
              "PSdR", "PSgR", "PSnL", "PSnR", "PSpL", "PSpR", "PTR", "PUL", 
              "PUR", "PWL", "PWR", "PYL", "PYR", "PyrL", "PyrR", "R*DL", "R*FL", 
              "R*FR", "R*gnR", "R*L", "R*mbL", "R*MR", "R*NL", "R*OR", "R*PR", 
              "R*SdL", "R*SgL", "R*SgR", "R*SnL", "R*SnR", "R*SpR", "R*SrR", 
              "R*SyL", "R*WL", "R*WR", "R*YR", "RBL", "RbmL", "RbmR", "RBR", 
              "rdBL", "rdDL", "rdGL", "RdgL", "RdgR", "RDL", "RDR", "RdrL", 
              "RdyL", "RgdL", "RGL", "RgnL", "RGR", "RmbR", "RML", "RMR", "rnBL", 
              "rnDL", "rnGL", "RngL", "RngR", "RNL", "rnML", "rnNL", "rnOL", 
              "RnoL", "rnPL", "RNR", "ROL", "ROR", "RPL", "RPR", "RrdL", "RRL", 
              "RRR", "RryR", "RSdL", "RSdR", "RSgL", "RSgR", "RSnL", "RSnR", 
              "RSpL", "RSpR", "RUL", "RUR", "RWL", "RWR", "ryBL", "ryBR", "ryDL", 
              "ryDR", "ryFR", "ryGL", "ryGR", "RYL", "ryML", "ryNL", "ryOL", 
              "ryPL", "RYR", "ryRL", "RyrL", "RyrR", "ryWL", "ryYL", "SdB*L", 
              "SdBL", "SdBR", "SdDL", "SdDR", "SdFL", "SdFR", "SdG*L", "SdGL", 
              "SdGR", "SdML", "SdMR", "SdN*L", "SdN*R", "SdNL", "SdNR", "SdOL", 
              "SdOR", "SdP*L", "SdP*R", "SdPL", "SdPR", "SdR*L", "SdR*R", "SdRL", 
              "SdRR", "SdUL", "SdUR", "SdW*L", "SdW*R", "SdWL", "SdWR", "SdY*L", 
              "SdY*R", "SdYL", "SdYR", "SgB*L", "SgB*R", "SgBL", "SgBR", "SgDL", 
              "SgDR", "SgG*L", "SgG*R", "SgGL", "SgGR", "SgML", "SgMR", "SgN*L", 
              "SgN*R", "SgNL", "SgNR", "SgOL", "SgOR", "SgP*L", "SgPL", "SgPR", 
              "SgR*L", "SgR*R", "SgRL", "SgRR", "SgSgL", "SgSnL", "SgSnR", 
              "SgSpL", "SgTL", "SgW*L", "SgW*R", "SgWL", "SgWR", "SgYL", "SgYR", 
              "SnB*L", "SnBL", "SnBR", "SnDL", "SnDR", "SnFL", "SnFR", "SnG*L", 
              "SnG*R", "SnGL", "SnGR", "SnML", "SnMR", "SnN*R", "SnNL", "SnNR", 
              "SnOL", "SnOR", "SnP*L", "SnP*R", "SnPL", "SnPR", "SnR*L", "SnR*R", 
              "SnRL", "SnRR", "SnSgR", "SnSnL", "SnSpL", "SnSpR", "SnUL", "SnUR", 
              "SnW*L", "SnW*R", "SnWL", "SnWR", "SnY*L", "SnY*R", "SnYL", "SnYR", 
              "SpB*L", "SpB*R", "SpBL", "SpBR", "SpDL", "SpDR", "SpFL", "SpFR", 
              "SpG*L", "SpGL", "SpGR", "SpML", "SpMR", "SpN*R", "SpNL", "SpNR", 
              "SpOL", "SpOR", "SpP*L", "SpP*R", "SpPL", "SpR*R", "SpRL", "SpRR", 
              "SpSgL", "SpSgR", "SpSnL", "SpSnR", "SpSpL", "SpSpR", "SpUL", 
              "SpUR", "SpW*R", "SpWL", "SpWR", "SpY*L", "SpY*R", "SpYL", "SpYR", 
              "SrB*L", "SrB*R", "SrG*L", "SrG*R", "SrN*L", "SrN*R", "SrP*L", 
              "SrP*R", "SrR*L", "SrR*R", "SrW*L", "SrW*R", "SrY*L", "SrY*R", 
              "SyB*L", "SyB*R", "SyG*L", "SyN*L", "SyP*L", "SyP*R", "SyR*L", 
              "SyR*R", "SyW*L", "SyW*R", "SyY*L", "SyY*R", "TRL", "UB*L", "UB*R", 
              "UbmL", "UbmR", "UDL", "UDR", "UFL", "UFR", "UG*L", "UG*R", "UgdL", 
              "UgdR", "UGL", "UgnR", "UmbL", "UmbR", "UML", "UMR", "UN*R", 
              "UngL", "UngR", "UNL", "UOL", "UOR", "UP*L", "UP*R", "UPL", "UPR", 
              "UR*L", "UR*R", "URL", "URR", "USdL", "USdR", "USnL", "USnR", 
              "USpL", "USpR", "UUL", "UUR", "UW*R", "UWL", "UY*L", "UYL", "UYR", 
              "W*BL", "W*FL", "W*FR", "W*gdR", "W*gnL", "W*gnR", "W*GR", "W*mbL", 
              "W*MR", "W*NL", "W*OR", "W*PL", "W*PR", "W*RR", "W*SdL", "W*SdR", 
              "W*SgL", "W*SnL", "W*SnR", "W*SpR", "W*SrR", "W*SyL", "W*SyR", 
              "WBL", "WbmL", "WbmR", "WBR", "WdgL", "WdgR", "WDL", "WDR", "WdrL", 
              "WdyL", "WgdL", "WgdR", "WGL", "WmbR", "WML", "WMR", "WngL", 
              "WngR", "WNL", "WnoL", "WNR", "WOL", "WOR", "WPL", "WPR", "WrdL", 
              "WRL", "WRR", "WryR", "WSdL", "WSdR", "WSgL", "WSgR", "WSnL", 
              "WSnR", "WSpL", "WSpR", "WUL", "WUR", "WWL", "WWR", "WYL", "WYR", 
              "WyrL", "WyrR", "Y*DR", "Y*FL", "Y*gdR", "Y*NR", "Y*PL", "Y*RL", 
              "Y*RR", "Y*SdL", "Y*SgL", "Y*SgR", "Y*SnL", "Y*SnR", "Y*SpL", 
              "Y*SpR", "Y*SrR", "Y*SyL", "Y*SyR", "Y*UL", "Y*YR", "YBL", "YbmL", 
              "YbmR", "YBR", "ydBL", "ydBR", "ydDL", "ydGL", "YdgL", "YdgR", 
              "YDL", "ydML", "ydNL", "ydOL", "ydPL", "YDR", "YdrL", "YdyL", 
              "YFL", "YFR", "YgdL", "YgdR", "YGL", "YGR", "YmbL", "YmbR", "YML", 
              "YMR", "YngL", "YngR", "YNL", "YnoL", "YNR", "YOL", "YonL", "YOR", 
              "YPL", "YPR", "yrBL", "yrBR", "yrDL", "YrdL", "yrDR", "yrGL", 
              "yrGR", "YRL", "yrML", "yrMR", "yrNL", "yrNR", "yrOL", "yrPL", 
              "YRR", "yrRL", "yrUL", "yrWL", "yrYL", "YryR", "YSdL", "YSdR", 
              "YSgL", "YSgR", "YSnL", "YSpL", "YSpR", "YUL", "YUR", "YWL", 
              "YWR", "YYL", "YYR", "YyrL", "YyrR", "Unlisted"))
